// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObceImport.Models;

namespace ObceImport.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ObceImport.Models.District", b =>
                {
                    b.Property<string>("LAU1")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("NUTS3")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LAU1");

                    b.HasIndex("NUTS3");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("ObceImport.Models.Municipality", b =>
                {
                    b.Property<string>("LAU2")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("LAU1")
                        .IsRequired()
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LAU2");

                    b.HasIndex("LAU1");

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("ObceImport.Models.Population", b =>
                {
                    b.Property<string>("LAU2")
                        .HasColumnType("varchar(6)")
                        .HasMaxLength(6);

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.Property<double>("Age")
                        .HasColumnType("double");

                    b.Property<int>("Men")
                        .HasColumnType("int");

                    b.Property<double>("MensAge")
                        .HasColumnType("double");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int>("Women")
                        .HasColumnType("int");

                    b.Property<double>("WomensAge")
                        .HasColumnType("double");

                    b.HasKey("LAU2", "Year");

                    b.ToTable("Populations");
                });

            modelBuilder.Entity("ObceImport.Models.Region", b =>
                {
                    b.Property<string>("NUTS3")
                        .HasColumnType("varchar(5)")
                        .HasMaxLength(5);

                    b.Property<string>("LAU2")
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NUTS3");

                    b.HasIndex("LAU2");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("ObceImport.Models.District", b =>
                {
                    b.HasOne("ObceImport.Models.Region", "Region")
                        .WithMany("Districts")
                        .HasForeignKey("NUTS3")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObceImport.Models.Municipality", b =>
                {
                    b.HasOne("ObceImport.Models.District", "District")
                        .WithMany("Municipalities")
                        .HasForeignKey("LAU1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObceImport.Models.Population", b =>
                {
                    b.HasOne("ObceImport.Models.Municipality", "Municipality")
                        .WithMany("PopulationData")
                        .HasForeignKey("LAU2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ObceImport.Models.Region", b =>
                {
                    b.HasOne("ObceImport.Models.Municipality", "Capital")
                        .WithMany()
                        .HasForeignKey("LAU2");
                });
#pragma warning restore 612, 618
        }
    }
}
